version: 2.1
workflows:
  version: 2
  run-all-tests:
    jobs:
      - run-chrome-tests:
          context: messenger-end-to-end

  run-only-chrome:
    when:
      and:
        - equal: [ chrome, << pipeline.parameters.browser >> ]
    jobs:
      - run-chrome-tests:
          context: messenger-end-to-end

jobs:
  run-chrome-tests:
    docker:
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: Chrome
          name: "Run chrome tests"
      - store_artifacts:
          path: ~/project/artifacts