version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-23;google_apis;x86"
      - run:
          name: Launch emulator
          command: avdmanager create avd --name $name --package "system-images;android-23;google_apis;x86"
          background: true
      - run:
          name: Launch emulator
          command: emulator -avd test
      - run:
          command: |
            npm install
            npm i cross-env -g
            npm install -g allure-commandline
            npm run tests
          environment:
            BROWSER_NAME: Chrome
          name: "Run chrome tests"
      - store_artifacts:
          path: ~/project/artifacts